### ISSUE TITLE
can you please share the slides/notes for those who cannot attend the talk?

### ISSUE THREAD

**Issue by neiljaywarner** [rapPayne/react-native-vs-flutter#1]
can you please share the slides/notes for those who cannot attend the talk and for sharing with our teams?  (Thanks for doing it by the way)

thanks

**Comment by rapPayne** [comment]
Absolutely, Neil! Ask and you'll receive: [The presentation as a Medium article](https://medium.com/@rapPayne/react-native-or-flutter-which-should-i-choose-48567ae2e5e1).

This is part one of three. When all three are uploaded to the Flutter Community on Medium.com, you'll have the entire talk. Follow [https://medium.com/flutter-community](https://medium.com/flutter-community) to see them when they're ready to go.

**Comment by neiljaywarner** [comment]
@rapPayne  Thanks so much!  Great article, great job. I hope it is not too bold for me to make a few small suggestions please?
1) almost all of the links have issues in your article -you click on them and you do not get what you expect b/c of formatting issues.

2) Perhaps either flutter's popularity could be upgraded to "low to medium" or its growth to "Increasing rapidly" or both?
please consider: 
a) https://twitter.com/gpeal8/status/1077272379162804224
b) https://trends.google.com/trends/explore?cat=31&q=flutter,react-native . (flutter trends twice as high the last 12 months)

and concerning your specific metrics in the table
Stackoverflow questions and github stars. - the differences since the table to today seem significant


 growth in SO 
RN - 4k - approx 10%
Flutter- 4.3k - approx 50%

Github star growth
* RN - 2.6k - 3% or so
* Flutter - 8.3k- 12%or so

So if the SO question growth of flutter is 4x as fast (which counts devs new to it and old to it) and star growth is 4 times as fast, then the momentum is still very high.

Thank you so much.  
If this is the wrong place to put this, let me know and i can delete it and email you or send it somewhere else,etc. thanks

i'm looking forward to parts 2 and 3 for sure

**Comment by karlhorky** [comment]
Another thing that may be interesting to add to the article / research is the possibility of using TypeScript with React Native (which addresses the issue that Flutter + Dart provides types and JS does not)

**Comment by karlhorky** [comment]
I've opened a PR to add links to the content of the Medium posts here: https://github.com/rapPayne/react-native-vs-flutter/pull/18
