### ISSUE TITLE
Possible enhancement - post lines of code metrics for both

### ISSUE THREAD

**Issue by neiljaywarner** [rapPayne/react-native-vs-flutter#2]
do you think it would be worth running cloc or whatever to compare lines of code? or do you think it's nearly the same? 

I have heard flutter often beats native android or native iOS by a lot...

**Comment by karlhorky** [comment]
Looks like this metric is available on [Flutter, React Native & Felgo: Cross-platform Framework Comparison](https://github.com/FelgoSDK/Flutter-ReactNative-Felgo-Comparison), which uses this same codebase:

![Screen Shot 2021-06-26 at 17 26 48](https://user-images.githubusercontent.com/1935696/123517894-cf3fa480-d6a3-11eb-8263-fe2bc4faac19.png)

**Comment by karlhorky** [comment]
I've opened a PR to add this image to the readme: https://github.com/rapPayne/react-native-vs-flutter/pull/18
